default:
    py_version: "python3/bin/python"
    liwc_f_name: "conv_LSM_df_LIWC2015_Results_notext.csv"
    liwc_f_V2_name: "conv_LSM_df_LIWC2015_Results_Update.xlsx"
    ECHO_LSM_MLM_name: "ECHO_LSM_MLM.csv"
    ECHO_LSM_TbyT_name: "ECHO_LSM_TbyT.csv"
    ECHO_Transcript_name: "ECHO1_transcripts_complete.csv"
    ECHO_survey_data_name: "echo1.dta"
    ECHO_ID_key_name: "ECHO_ID_key.csv"
    ECHO_LSM_TbyT_Smoothed_name: "ECHO_LSM_TbyT_SMOOTHED.CSV"
    ECHO_LSM_MLM_chunks_wc_name: "ECHO_LSM_MLM_chunks_wc.csv"
    ECHO_LSM_MLM_chunks_turns_name: "ECHO_LSM_MLM_chunks_turns.csv"
    maripohsa_survey_data_name: "merged MaRIPOHSA data (patient_level 3-9-22).dta"
    
mike:
    transcript_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/Analysis/Maripohsa_transcripts'
    annies_role_file: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/MaRIPOHSA_Transcripts_SpeakerRole_Annie.csv'
    liwc_f_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/Analysis'
    liwc_f_V2_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/Analysis'
    ECHO_LSM_MLM_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_LSM_TbyT_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_LSM_TbyT_Smoothed_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_Transcript_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_survey_data_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_ID_key_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_LSM_MLM_chunks_wc_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_LSM_MLM_chunks_turns_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/ECHO1_Study'
    maripohsa_survey_data_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Patient _Provider_Communication_Projects/Analysis'
    
salar:
    transcript_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/Analysis/Maripohsa_transcripts'
    annies_role_file: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/MaRIPOHSA_Transcripts_SpeakerRole_Annie.csv'
    liwc_f_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/Analysis'
    liwc_f_V2_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/Analysis'
    ECHO_LSM_MLM_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_LSM_TbyT_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_LSM_TbyT_Smoothed_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_Transcript_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_survey_data_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_ID_key_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_LSM_MLM_chunks_wc_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/ECHO1_Study'
    ECHO_LSM_MLM_chunks_turns_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/ECHO1_Study'
    maripohsa_survey_data_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Patient _Provider_Communication_Projects/Analysis'
